yolo_model:

  config_file:
    name: yolov2-tiny.cfg
  weight_file:
    name: yolo-obj.weights
  threshold:
    value: 0.1
  detection_classes:
    names:
      - CDY
      - CFR
      - CSV
      - SVB
      - SYH